version: 2
updates:
  # Enable version updates for npm (Yarn)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      otel:
        applies-to: version-updates
        patterns:
          - "@opentelemetry/*"
      mastra:
        applies-to: version-updates
        patterns:
          - "mastra"
          - "@mastra/*"
      ai-sdk:
        applies-to: version-updates
        patterns:
          - "ai"
          - "@ai-sdk/*"
    # Ignore specific packages if needed (uncomment and modify as needed)
    # ignore:
    #   - dependency-name: "package-name"
    #     update-types: ["version-update:semver-major"]

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"


