command_type: test

modules:
  - name: evergreen
    owner: evergreen-ci
    repo: evergreen
    branch: main
    auto_update: true

ignore:
  - "*.md"
  - ".github/*"

pre:
  - func: assume-ec2-role
  - func: get-project
  - func: setup-node
  - func: pnpm-install
post:
  - func: assume-ec2-role
  - func: attach-mongod-logs
  - func: attach-test-results

buildvariants:
  - name: ubuntu2204-small
    display_name: Ubuntu 22.04
    run_on:
      - ubuntu2204-small
    expansions:
      mongodb_tools_url: https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.11.0.tgz
      mongodb_url_2204: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-8.0.4.tgz
      mongosh_url_2204: https://downloads.mongodb.com/compass/mongosh-2.3.1-linux-x64.tgz
      node_version: 22.14.0
      goroot: /opt/golang/go1.24
    modules:
      - evergreen
    tasks:
      - name: write_and_set_downstream_expansions
      - name: compile
      - name: lint
      - name: check-generated-cursor-client
      - name: test
      - name: e2e
      - name: check-mastra-dev-startup
      - name: check-sage-prod-startup
      - name: evergreen-evals
      - name: question-classifier-evals
      - name: log-analyzer-workflow-evals
      - name: sage-thinking-evals
      - name: slack-thread-summarizer-evals
      - name: slack-question-ownership-evals
      - name: release-notes-evals
    display_tasks:
      - name: evals
        execution_tasks:
          - "evergreen-evals"
          - "question-classifier-evals"
          - "log-analyzer-workflow-evals"
          - "sage-thinking-evals"
          - "slack-thread-summarizer-evals"
          - "slack-question-ownership-evals"
          - "release-notes-evals"
tasks:
  - name: write_and_set_downstream_expansions
    commands:
      - func: write repo name to downstream_expansions.yaml for Pine
      - command: downstream_expansions.set
        params:
          file: downstream_expansions.yaml
  - name: compile
    commands:
      - func: pnpm-build
  - name: lint
    commands:
      - func: pnpm-lint
  - name: check-generated-cursor-client
    commands:
      - func: check-generated-cursor-client
  - name: test
    commands:
      - func: pnpm-test
  - name: e2e
    commands:
      - func: setup-mongodb
      - func: run-make-background
        vars:
          target: local-evergreen
      - func: symlink
      - func: pnpm-build
      - func: wait-for-evergreen
      - func: pnpm-e2e
  - name: check-mastra-dev-startup
    commands:
      - func: pnpm-build
      - func: mastra-dev-startup
  - name: check-sage-prod-startup
    commands:
      - func: setup-mongodb
      - func: pnpm-build
      - func: sage-prod-startup
  - name: evergreen-evals
    commands:
      - func: setup-mongodb
      - func: run-make-background
        vars:
          target: local-evergreen
      - func: wait-for-evergreen
      - func: pnpm-eval
        vars:
          eval_dir: evergreenAgent
      - func: attach-braintrust-results
        vars:
          xml_file_name: evergreen_evals.xml
  - name: question-classifier-evals
    commands:
      - func: pnpm-eval
        vars:
          eval_dir: questionClassifierAgent
      - func: attach-braintrust-results
        vars:
          xml_file_name: question_classifier_evals.xml
  - name: log-analyzer-workflow-evals
    commands:
      - func: pnpm-eval
        vars:
          eval_dir: logAnalyzerWorkflow
      - func: attach-braintrust-results
        vars:
          xml_file_name: log_analyzer_workflow_evals.xml
  - name: sage-thinking-evals
    commands:
      - func: setup-mongodb
      - func: run-make-background
        vars:
          target: local-evergreen
      - func: wait-for-evergreen
      - func: pnpm-eval
        vars:
          eval_dir: sageThinkingAgent
      - func: attach-braintrust-results
        vars:
          xml_file_name: sage_thinking_evals.xml
  - name: slack-thread-summarizer-evals
    commands:
      - func: pnpm-eval
        vars:
          eval_dir: slackThreadSummarizerAgent
      - func: attach-braintrust-results
        vars:
          xml_file_name: slack_thread_summarizer_evals.xml
  - name: slack-question-ownership-evals
    commands:
      - func: pnpm-eval
        vars:
          eval_dir: questionOwnershipAgent
      - func: attach-braintrust-results
        vars:
          xml_file_name: slack_question_ownership_evals.xml
  - name: release-notes-evals
    commands:
      - func: pnpm-eval
        vars:
          eval_dir: releaseNotesWorkflow
      - func: attach-braintrust-results
        vars:
          xml_file_name: release_notes_evals.xml

functions:
  write repo name to downstream_expansions.yaml for Pine:
    - command: shell.exec
      params:
        script: |
          touch downstream_expansions.yaml
          echo "pine_repo_name: sage" | tee downstream_expansions.yaml

  attach-test-results:
    command: attach.xunit_results
    params:
      files:
        - "./sage/bin/test/*.xml"

  attach-braintrust-results:
    command: attach.xunit_results
    params:
      files:
        - ./sage/bin/${xml_file_name}

  attach-mongod-logs:
    command: s3.put
    type: system
    params:
      aws_key: ${AWS_ACCESS_KEY_ID}
      aws_secret: ${AWS_SECRET_ACCESS_KEY}
      aws_session_token: ${AWS_SESSION_TOKEN}
      local_file: "sage/evergreen/bin/mongod-logs.txt"
      remote_file: ${build_variant}/${task_id}/${execution}/mongod-logs.txt
      bucket: evg-bucket-sage
      content_type: text/plain
      permissions: public-read
      display_name: mongod-logs

  assume-ec2-role:
    command: ec2.assume_role
    params:
      role_arn: ${ASSUME_ROLE_ARN}

  get-project:
    command: git.get_project
    type: setup
    params:
      directory: sage
      shallow_clone: true

  health-check:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        ./scripts/health-check.sh

  run-make-background:
    command: subprocess.exec
    params:
      working_dir: sage/evergreen
      binary: make
      args: ["${make_args|}", "${target}"]
      background: true
      env:
        SETTINGS_OVERRIDE: file
        GOROOT: ${goroot}

  setup-mongodb:
    - command: subprocess.exec
      type: setup
      params:
        env:
          gobin: ${goroot}/bin/go
          MONGODB_URL: ${mongodb_url_2204}
          MONGODB_DECOMPRESS: ${decompress}
        working_dir: sage/evergreen
        command: make get-mongodb
    - command: subprocess.exec
      type: setup
      params:
        env:
          gobin: ${goroot}/bin/go
          MONGOSH_URL: ${mongosh_url_2204}
          MONGOSH_DECOMPRESS: ${decompress}
        working_dir: sage/evergreen
        command: make get-mongosh
    - command: shell.exec
      type: setup
      params:
        background: true
        # Turn off silent to enable DB logging for debugging purposes
        silent: true
        working_dir: sage/evergreen
        shell: bash
        script: | 
          mkdir -p bin
          make start-mongod > bin/mongod-logs.txt 2>&1
    - command: subprocess.exec
      type: setup
      params:
        working_dir: sage/evergreen
        command: make configure-mongod
    - command: shell.exec
      type: setup
      params:
        shell: bash
        script: |
          ${PREPARE_SHELL}
          cd $PROJECT_DIRECTORY
          mkdir mongodb-tools && cd mongodb-tools
          curl ${mongodb_tools_url} -o mongodb-tools.tgz
          ${decompress} mongodb-tools.tgz
          mv ./mongodb-*/bin/* .
  
  setup-node:
    - command: subprocess.exec
      params:
        binary: bash
        args:
          - sage/.evergreen/scripts/prepare-shell.sh
    - command: expansions.update
      params:
        file: expansion.yml
    - command: shell.exec
      params:
        exec_timeout_secs: 60
        shell: bash
        script: |
          ${PREPARE_SHELL}

          # Install pnpm via standalone script
          curl -fsSL https://get.pnpm.io/install.sh | env PNPM_HOME="$PNPM_HOME" SHELL="$(which bash)" bash -

          # pnpm env manages Node.js versions directly.
          # Retry the Node.js installation in case it flakes.
          for i in {1..5}; do
            pnpm env use --global ${node_version}
            [[ $? -eq 0 ]] && break
            echo "Attempt $i of 5 to install Node failed"
            sleep 10
          done

  symlink:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ln -s ${workdir}/evergreen/graphql/schema ${workdir}/sdlschema

  wait-for-evergreen:
    command: shell.exec
    type: setup
    params:
      exec_timeout_secs: 600
      working_dir: sage
      script: ./scripts/wait-for-evergreen.sh

  pnpm-build:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        pnpm build

  pnpm-install:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        pnpm install --frozen-lockfile
  
  pnpm-lint:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        pnpm eslint:strict

  check-generated-cursor-client:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        ./scripts/check-generated-cursor-client.sh

  pnpm-start:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        pnpm start

  pnpm-e2e:
    command: shell.exec
    params:
      env:
        AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
        AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
        BRAINTRUST_PROJECT_ID: ${BRAINTRUST_PROJECT_ID_STAGING}
        BRAINTRUST_API_KEY: ${BRAINTRUST_API_KEY}
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        pnpm e2e

  pnpm-test:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        pnpm test

  pnpm-eval:
    command: shell.exec
    params:
      working_dir: sage
      env:
        AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
        AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
        BRAINTRUST_API_KEY: ${BRAINTRUST_API_KEY}
        EVAL_DIR: ${eval_dir}
      shell: bash
      script: |
        ${PREPARE_SHELL}
        .evergreen/scripts/publish-evals.sh

  mastra-dev-startup:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        ./scripts/mastra-dev-startup.sh

  sage-prod-startup:
    command: shell.exec
    params:
      working_dir: sage
      shell: bash
      script: |
        ${PREPARE_SHELL}
        ./scripts/sage-prod-startup.sh
