apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sage
  description: Server powering the Evergreen AI Service.
  annotations:
    evergreen/project-id: 686d2f07ef37320007ad2596
  links:
    - url: https://github.com/evergreen-ci/sage
      title: evergreen-ci/sage
      icon: github
spec:
  type: service
  owner: group:default/10genevergreenui
  lifecycle: production
  system: evergreen
  consumesApis:
    - evergreen-api-graphql
    - evergreen-api-rest
  dependsOn:
    - component:Sentry
    - component:Honeycomb
    - component:evergreen-backend
    - component:braintrust

