---
apiVersion: service.kanopy-platform.github.io/v1beta1
kind: ServiceEntitlementRequest
metadata:
  name: sage-to-otel-collector
  namespace: devprod-evergreen
spec:
  serviceCatalogEntryRef:
    name: otel-collector-web-app
    namespace: devprod-platform
  source:
    principals:
      - "cluster.local/ns/devprod-evergreen/sa/sage-sa"
    workloadSelector:
      matchLabels:
        app: sage
  requestedPaths:
    - methods:
        - POST
      paths:
        - /v1/traces
        - /opentelemetry.proto.collector.trace.v1.TraceService/Export
        - /opentelemetry.proto.collector.logs.v1.LogsService/Export
        - /opentelemetry.proto.collector.metrics.v1.MetricsService/Export