arch: "amd64"

ingress:
  enabled: true
  hosts:
    - sage.devprod-evergreen.staging.corp.mongodb.com
service:
  targetPort: 8080
mesh:
  enabled: true
  
services:
  - name: http
    ingress: true
    port: 80
    probes: true
    protocol: TCP
    targetPort: 8080
    type: ClusterIP

resources:
  requests:
    cpu: 4
    memory: 8Gi
  limits:
    cpu: 8
    memory: 8Gi

env:
  EVERGREEN_API_USER: parsley-ai-skunkworks
  EVERGREEN_API_URL: https://evergreen.mongodb.com/rest/v2
  EVERGREEN_URL: https://evergreen.mongodb.com
  AZURE_OPENAI_API_VERSION: 2024-02-15-preview
  PORT: 8080
  OTEL_SERVICE_NAME: sage-ai-service
  OTEL_ENABLED: true
  OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector.staging.corp.mongodb.com:4317
  LOG_LEVEL: debug

envSecrets:
  AZURE_OPENAI_API_KEY: parsley-ai-secrets
  AZURE_OPENAI_ENDPOINT: parsley-ai-secrets
  EVERGREEN_API_KEY: parsley-ai-secrets
  MONGO_PASSWORD: parsley-ai-secrets
  MONGO_URL: parsley-ai-secrets
  MONGO_USERNAME: parsley-ai-secrets
