arch: "amd64"

ingress:
  enabled: true
  hosts:
    - sage.devprod-evergreen.staging.corp.mongodb.com
service:
  targetPort: 8080
mesh:
  enabled: true

services:
  - name: http
    ingress: true
    port: 80
    probes: true
    protocol: TCP
    targetPort: 8080
    type: ClusterIP

resources:
  requests:
    cpu: 4
    memory: 8Gi
  limits:
    cpu: 8
    memory: 8Gi

env:
  EVERGREEN_API_USER: parsley-ai-skunkworks
  EVERGREEN_API_URL: https://evergreen.mongodb.com/rest/v2
  EVERGREEN_URL: https://evergreen.mongodb.com
  AZURE_OPENAI_API_VERSION: 2024-02-15-preview
  PORT: 8080
  OTEL_COLLECTOR_URL: http://otel-collector-web-app.devprod-platform.svc.cluster.local:4318/v1/traces


envSecrets:
  AZURE_OPENAI_API_KEY: parsley-ai-secrets
  AZURE_OPENAI_ENDPOINT: parsley-ai-secrets
  EVERGREEN_API_KEY: parsley-ai-secrets
  MONGO_PASSWORD: parsley-ai-secrets
  MONGO_URL: parsley-ai-secrets
  MONGO_USERNAME: parsley-ai-secrets

serviceAccount:
  enabled: true
  serviceEntitlementRequests:
   - name: sage-web-app-to-devprod-platform-otel-collector-web-app
     serviceCatalogEntryRef:
       name: otel-collector-web-app
       namespace: devprod-platform
     requestedPaths:
     - methods:
       - POST
       paths:
       - /v1/traces
       - /opentelemetry.proto.collector.trace.v1.TraceService/Export
       - /opentelemetry.proto.collector.logs.v1.LogsService/Export
       - /opentelemetry.proto.collector.metrics.v1.MetricsService/Export