# Staging-specific configuration (merged with common.yaml)
# Only contains overrides and staging-specific values

ingress:
  enabled: true
  hosts:
    - sage.devprod-evergreen.staging.corp.mongodb.com

service:
  targetPort: 8080

mesh:
  enabled: true

services:
  - name: http
    ingress: true
    port: 80
    probes: true
    protocol: TCP
    targetPort: 8080
    type: ClusterIP

resources:
  requests:
    cpu: 1
    memory: 4Gi
  limits:
    cpu: 2
    memory: 8Gi

# Environment-specific variables
env:
  BRAINTRUST_PARENT: project_name:sage-staging
  BRAINTRUST_PROJECT_NAME: sage-staging
  NODE_ENV: staging
  PORT: 8080
  SENTRY_ENVIRONMENT: staging
  SENTRY_CAPTURE_CONSOLE: true

envSecrets:
  AZURE_OPENAI_API_KEY: parsley-ai-secrets
  AZURE_OPENAI_ENDPOINT: parsley-ai-secrets
  EVERGREEN_API_KEY: parsley-ai-secrets
  MONGODB_URI: parsley-ai-secrets
  OTEL_EXPORTER_OTLP_HEADERS: parsley-ai-secrets
  BRAINTRUST_API_KEY: parsley-ai-secrets
  HONEYCOMB_API_KEY: parsley-ai-secrets
  SENTRY_AUTH_TOKEN: parsley-ai-secrets
  VOYAGE_API_KEY: parsley-ai-secrets

serviceAccount:
  enabled: true

security: # No sensitive info; dummy data only.
  dataClassification: 'Public'
  dataDesignation: ['MI']

ownership:
  driEmail: evergreen-team@mongodb.com

