# Staging-specific configuration (merged with common.yaml)
# Only contains overrides and staging-specific values

ingress:
  enabled: true
  hosts:
    - sage.devprod-evergreen.staging.corp.mongodb.com

service:
  targetPort: 8080

mesh:
  enabled: true

services:
  - name: http
    ingress: true
    port: 80
    probes: true
    protocol: TCP
    targetPort: 8080
    type: ClusterIP

resources:
  requests:
    cpu: 1
    memory: 4Gi
  limits:
    cpu: 2
    memory: 8Gi

# Environment-specific variables
env:
  BRAINTRUST_PARENT: project_name:sage-staging
  BRAINTRUST_PROJECT_NAME: sage-staging
  JIRA_BASE_URL: https://jira-staging.corp.mongodb.com
  NODE_ENV: staging
  PORT: 8080
  SENTRY_ENVIRONMENT: staging
  SENTRY_CAPTURE_CONSOLE: true
