/**
 * Script to generate the public projects TypeScript file from the live Jira API.
 *
 * Usage: pnpm generate:public-projects
 *
 * This makes an unauthenticated request to the Jira API to get the list
 * of publicly visible projects and generates src/generated/public-projects/index.ts.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const JIRA_BASE_URL = 'https://jira.mongodb.org';
const OUTPUT_DIR = path.join(__dirname, '../src/generated/public-projects');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'index.ts');

const fetchPublicProjects = async (): Promise<string[]> => {
  const url = `${JIRA_BASE_URL}/rest/api/2/project`;

  const response = await fetch(url, {
    method: 'GET',
    headers: {
      Accept: 'application/json',
    },
  });

  if (!response.ok) {
    throw new Error(
      `Failed to fetch public projects: ${response.status} ${response.statusText}`
    );
  }

  const projects = (await response.json()) as Array<{ key: string }>;
  return projects.map(p => p.key).sort();
};

const generateTypeScriptContent = (projectKeys: string[]): string => {
  const projectList = projectKeys.map(key => `  '${key}',`).join('\n');

  return `/**
 * Auto-generated file. Do not edit manually.
 * Generated by: pnpm generate:public-projects
 *
 * Publicly accessible Jira project keys (visible without authentication).
 * These projects are visible to anonymous users on jira.mongodb.org.
 */

export const PUBLIC_PROJECT_KEYS = new Set([
${projectList}
]);
`;
};

const main = async (): Promise<void> => {
  console.log('Fetching public projects from Jira API...\n');

  const projectKeys = await fetchPublicProjects();

  console.log(`Found ${projectKeys.length} public projects:`);
  projectKeys.forEach(key => console.log(`  - ${key}`));
  console.log('');

  // Ensure output directory exists
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  const content = generateTypeScriptContent(projectKeys);
  fs.writeFileSync(OUTPUT_FILE, content);

  console.log(`Updated ${OUTPUT_FILE}`);
};

main().catch(error => {
  console.error('Error:', error.message);
  process.exit(1);
});
